# Generated by Django 4.1.7 on 2023-03-15 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('title_group_name', models.CharField(max_length=100, verbose_name='Titulo do Grupo')),
                ('completed_service', models.BooleanField(verbose_name='Atendimeno Finalizado')),
                ('messages', models.JSONField(verbose_name='Mensagens')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_calls', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
